### ISSUE TITLE
Min/max dates

### ISSUE THREAD

**Issue by jonespen** [Kilix/okami#8]
Hey, great library!

Is it possible to set max/min dates for the Calendar? Want to use this to build a range picker. If not, I could submit a PR if you're interested?

**Comment by AugustinLF** [comment]
Thanks! Hmmm, I'm not sure of what you mean? Since most of the rendering is done by the user (you), this should be doable on the user-land, no ? You can block the navigation, and when rendering your days, you can probably make them unclickable, no?

But of course, if what you want requires modifications to Okami, I'll gladly accept it :)

Could you perhaps give me an example?

**Comment by AugustinLF** [comment]
Btw, I know you talk of a range picker, but here is an [example](https://codesandbox.io/embed/m7wrq8lj0y) of okami (with downshift) as a date picker.

**Comment by jonespen** [comment]
Ah, of course! Sorry, I can mos def do it the rendering. No need to pollute okami with this ;)

**Comment by AugustinLF** [comment]
Glad to hear that! I'd be happy to hear about your experience with that, since Okami is still pretty recent, we didn't get a lot feedback yet :)
